#!/bin/bash

PROJECT_ID=$(gcloud config get-value project)
PROJECT_NUMBER=$(gcloud projects describe $(gcloud config get-value project) --format='value(projectNumber)')
REGION="us-central1"
LOCATION="us-central1"
DEFAULT_SVC_ACCOUNT_EMAIL="$PROJECT_NUMBER-compute@developer.gserviceaccount.com"

APP_NAME="$PROJECT_ID-bq-eventarc-driven-queries"
BUCKET=$APP_NAME

DATA_FILE_CSV=loan_201.csv

BQ_DATASET=bq_eventarc_queries_demo
BQ_TABLE_DATA=loan_201

SVC_ACCOUNT_NAME=$APP_NAME
SVC_ACCOUNT_EMAIL="$APP_NAME@$PROJECT_ID.iam.gserviceaccount.com"
# DOCKER_REPO="$APP_NAME-repo"
# IMAGE_NAME="$APP_NAME-image"
# IMAGE_TAG="latest"
# IMAGE_URI="$REGION-docker.pkg.dev/$PROJECT_ID/$DOCKER_REPO/$IMAGE_NAME:$IMAGE_TAG"
# CLOUD_RUN_SERVICE_NAME="$APP_NAME"
CLOUD_FUNCTION_NAME="$APP_NAME"

echo "==================== args ====================================================================="
echo "PROJECT_ID:                  " $PROJECT_ID
echo "PROJECT_NUMBER:              " $PROJECT_NUMBER
echo "REGION:                      " $REGION
echo "DEFAULT_SVC_ACCOUNT_EMAIL:   " $DEFAULT_SVC_ACCOUNT_EMAIL
echo "APP_NAME:                    " $APP_NAME
echo "BUCKET:                      " $BUCKET
echo "DATA_FILE_CSV:               " $DATA_FILE_CSV
echo "BQ_DATASET:                  " $BQ_DATASET
echo "BQ_TABLE_DATA:               " $BQ_TABLE_DATA
echo "SVC_ACCOUNT_NAME:            " $SVC_ACCOUNT_NAME
echo "SVC_ACCOUNT_EMAIL:           " $SVC_ACCOUNT_EMAIL
# echo "DOCKER_REPO:                 " $DOCKER_REPO
# echo "IMAGE_NAME:                  " $IMAGE_NAME
# echo "IMAGE_TAG:                   " $IMAGE_TAG
# echo "IMAGE_URI:                   " $IMAGE_URI
# echo "CLOUD_RUN_SERVICE_NAME:      " $CLOUD_RUN_SERVICE_NAME
echo "CLOUD_FUNCTION_NAME:         " $CLOUD_FUNCTION_NAME
echo "================================================================================================="